services:
  sheep-dog-dev-db:
    image: farhan5248/sheep-dog-dev-db:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mbt-pass
    ports:
     - 3307:3306
    labels:
      stack.name: "sheep-dog-dev-stack"
    networks:
      - sheepdognet
  sheep-dog-dev-mq:
    image: apache/activemq-artemis:latest-alpine
    restart: unless-stopped
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
    ports:
      - 61617:61616
      - 8167:8161
    labels:
      stack.name: "sheep-dog-dev-stack"
    networks:
      - sheepdognet
  sheep-dog-dev-svc:
    image: farhan5248/sheep-dog-dev-svc:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/getFileList"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      sheep-dog-dev-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sheep-dog-dev-db:3306/mbt
    ports:
      - 8087:8080
    labels:
      stack.name: "sheep-dog-dev-stack"
    networks:
      - sheepdognet
networks:
  sheepdognet:
    driver: bridge
