apiVersion: v1
kind: Service
metadata:
  name: sheep-dog-dev-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    app: sheep-dog-dev-db
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheep-dog-dev-db
spec:
  selector:
    matchLabels:
      app: sheep-dog-dev-db
  template:
    metadata:
      labels:
        app: sheep-dog-dev-db
    spec:
      containers:
        - name: mysql
          image: farhan5248/sheep-dog-dev-db:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mbt-pass
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: sheep-dog-dev-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: sheep-dog-dev-svc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheep-dog-dev-svc
spec:
  selector:
    matchLabels:
      app: sheep-dog-dev-svc
  template:
    metadata:
      labels:
        app: sheep-dog-dev-svc
    spec:
      containers:
        - name: service
          image: farhan5248/sheep-dog-dev-svc:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://sheep-dog-dev-db:3306/mbt
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /getFileList
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3