apiVersion: v1
kind: Namespace
metadata:
  name: sheep-dog-dev
---
apiVersion: v1
kind: Service
metadata:
  name: sheep-dog-dev-db
  namespace: sheep-dog-dev
  labels:
    app: sheep-dog-dev
spec:
  selector:
    app: sheep-dog-dev
  ports:
    - name: sheep-dog-dev-db
      port: 3306
      targetPort: 3306
      nodePort: 30306
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: sheep-dog-dev-svc
  namespace: sheep-dog-dev
  labels:
    app: sheep-dog-dev
spec:
  selector:
    app: sheep-dog-dev
  ports:
    - name: sheep-dog-dev-svc
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheep-dog-dev
  namespace: sheep-dog-dev
  labels:
    app: sheep-dog-dev
spec:
  selector:
    matchLabels:
      app: sheep-dog-dev
  template:
    metadata:
      labels:
        app: sheep-dog-dev
    spec:
      containers:
        - name: sheep-dog-dev-db
          image: farhan5248/sheep-dog-dev-db:latest
          imagePullPolicy: "Always"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sheep-dog-dev-secrets
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - "mysql -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
        - name: sheep-dog-dev-svc
          image: farhan5248/sheep-dog-dev-svc:latest
          imagePullPolicy: "Always"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://sheep-dog-dev-db:3306/mbt
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
