namespace: failsafe
resources:
  - ../../../../sheep-dog-specs/docker/base
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: sheep-dog-dev-ingress
  - path: service-patch-db.yaml
    target:
      kind: Service
      name: sheep-dog-dev-db