name: Publish Cucumber Xtext Editor
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven
    - name: Build and install Cucumber Xtext Editor
      working-directory: ./cucumberxtexteditor.parent
      run: mvn clean deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       