name: Publish MBT Maven Plugin


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and install MBT Maven Plugin
      working-directory: ./mbt-maven-plugin
      run: mvn clean deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          