name: Publish MBT Transformer
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and install MBT Transformer
      working-directory: ./mbt-transformer
      run: mvn clean deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}