name: Merge

on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    runs-on: [farhan5248-runners, linux]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Git
      run: |
        git config --local user.name "${{ secrets.ACTIONS_BOT_NAME }}"
        git config --local user.email "${{ secrets.ACTIONS_BOT_EMAIL }}"
    - name: Merge develop into main
      run: |
        git fetch origin
        git checkout main
        git merge origin/develop
        git push origin main
      env:
        GITHUB_TOKEN: ${{ github.token }}
