name: Release

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Release plugin organisation'
        required: true
        type: choice
        options:
          - Maven
          - Sheep
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.9'
    - name: Configure Git User
      run: |
        git config --local user.name "${{ secrets.ACTIONS_BOT_NAME }}"
        git config --local user.email "${{ secrets.ACTIONS_BOT_EMAIL }}"
    - name: Run Maven
      working-directory: ./sheepdogxtextplugin.parent
      run: |
       mvn org.codehaus.mojo:versions-maven-plugin:update-properties -DallowSnapshots=false -DallowDowngrade=true -s $GITHUB_WORKSPACE/settings.xml
       mvn org.farhan:sheep-dog-mgmt-maven-plugin:1.6-SNAPSHOT:prepare -DpreparationGoals=clean,deploy -s $GITHUB_WORKSPACE/settings.xml
       git push
       mvn org.codehaus.mojo:versions-maven-plugin:update-properties -DallowSnapshots=true -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
