name: Release

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
        type: choice
        options:
          - sheep-dog-mgmt-maven-plugin
          - sheep-dog-dev
          - sheep-dog-dev-maven-plugin
          - sheep-dog-dev-svc
          - sheep-dog-dev-svc-maven-plugin
          - sheep-dog-test
          - sheepdogxtextcukeplugin.parent
          - sheepdogxtextplugin.parent
      plugin:
        description: 'Release plugin organisation'
        required: true
        type: choice
        options:
          - Maven
          - Sheep
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.9'
    - name: Configure Git User
      run: |
        git config --local user.name "${{ secrets.ACTIONS_BOT_NAME }}"
        git config --local user.email "${{ secrets.ACTIONS_BOT_EMAIL }}"
    - name: Update to Release versions
      working-directory: ./${{ inputs.project }}
      run: |
        mvn org.codehaus.mojo:versions-maven-plugin:update-properties -DallowSnapshots=false -DallowDowngrade=true
    - name: Run Maven Release
      working-directory: ./${{ inputs.project }}
      run: |
        if [ ${{ inputs.plugin }} == Maven ]; then
          mvn -B release:prepare -DcheckModificationExcludeList=pom.xml -DpreparationGoals=deploy -s $GITHUB_WORKSPACE/settings.xml
        else
          mvn org.farhan:sheep-dog-mgmt-maven-plugin:1.14-SNAPSHOT:prepare -DpreparationGoals=deploy -s $GITHUB_WORKSPACE/settings.xml
        fi
    - name: Update to SNAPSHOT versions
      working-directory: ./${{ inputs.project }}
      run: |
        mvn org.codehaus.mojo:versions-maven-plugin:update-properties -DallowSnapshots=true
        mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        if [[ $(git status --porcelain --untracked-files=no | wc -l) -gt 0 ]]; then
          git add pom.xml
          git commit -m "Upgrading dependency versions"
        fi
        git push
      env:
        GITHUB_TOKEN: ${{ github.token }}
