name: Publish Sheep Dog Test Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'sheep-dog-test/**'
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-test:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-test'
    secrets: inherit