name: Publish Sheep Dog Snapshot

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
    paths:
      - '.github/**'
      - '**/docker/**'
      - '**/src/**'
      - '**/pom.xml'
permissions:
  contents: read
  packages: write

jobs:
  sheep-dog-test:
    uses: ./.github/workflows/snapshot.yml
    with:
      project: 'sheep-dog-test'

  sheep-dog-xtext-plugin:
    needs: [sheep-dog-test]
    uses: ./.github/workflows/snapshot.yml
    with:
      project: 'sheep-dog-xtext-plugin'

  sheep-dog-xtext-cuke-plugin:
    needs: [sheep-dog-test]
    uses: ./.github/workflows/snapshot.yml
    with:
      project: 'sheep-dog-xtext-cuke-plugin'

  sheep-dog-dev:
    needs: [sheep-dog-xtext-plugin, sheep-dog-xtext-cuke-plugin]
    uses: ./.github/workflows/snapshot.yml
    with:
      project: 'sheep-dog-dev'

  sheep-dog-dev-maven-plugin:
    needs: [sheep-dog-dev]
    uses: ./.github/workflows/snapshot.yml
    with:
      project: 'sheep-dog-dev-maven-plugin'

  sheep-dog-dev-svc:
    needs: [sheep-dog-dev]
    uses: ./.github/workflows/snapshot.yml
    with:
      project: 'sheep-dog-dev-svc'

  sheep-dog-dev-svc-maven-plugin:
    needs: [sheep-dog-dev-svc]
    uses: ./.github/workflows/snapshot.yml
    with:
      project: 'sheep-dog-dev-svc-maven-plugin'   
