name: Publish Sheep Dog Management Maven Plugin

on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: farhan5248-runners
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.9'
    - name: Run Maven
      working-directory: ./sheep-dog-mgmt-maven-plugin
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
