name: Publish Sheep Dog Dev Maven Plugin Release

on:
  workflow_run:
    workflows: ["Publish Sheep Dog Dev Release"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'sheep-dog-dev-maven-plugin/**'
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-dev-maven-plugin:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-maven-plugin'
      plugin: 'Maven'
    secrets: inherit