name: Publish Sheep Dog Management Maven Plugin

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'sheep-dog-mgmt-maven-plugin/**'
    paths-ignore:
      - 'scripts/**'
permissions:
  contents: write
  packages: write
jobs:
  sheep-dog-test:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-mgmt-maven-plugin'
      plugin: 'Maven'
    secrets: inherit
