name: Publish Sheep Dog Dev Service Maven Plugin Release

on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-dev-svc-maven-plugin:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-svc-maven-plugin'
      plugin: 'Maven'
    secrets: inherit