name: Publish Sheep Dog Dev Maven Plugin Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'sheep-dog-dev-maven-plugin/**'
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-dev-maven-plugin:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-maven-plugin'
      plugin: 'Maven'
    secrets: inherit