name: Publish Sheep Dog Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  sheep-dog-test:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/sheep-dog-test.yml

  sheep-dog-xtext-plugin:
    needs: [sheep-dog-test]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/sheep-dog-xtext-plugin.yml

  sheep-dog-xtext-cuke-plugin:
    needs: [sheep-dog-test]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/sheep-dog-xtext-cuke-plugin.yml

  sheep-dog-dev:
    needs: [sheep-dog-xtext-plugin, sheep-dog-xtext-cuke-plugin]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/sheep-dog-dev.yml
