name: Publish Sheep Dog Xtext Plugin Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'sheepdogxtextplugin.parent/**'
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-xtext-plugin:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheepdogxtextplugin.parent'
      plugin: 'Sheep'
    secrets: inherit

  sheep-dog-dev:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev'
      plugin: 'Maven'
    secrets: inherit

  sheep-dog-dev-maven-plugin:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-maven-plugin'
      plugin: 'Maven'
    secrets: inherit    

  sheep-dog-dev-svc:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-svc'
      plugin: 'Maven'
    secrets: inherit
  
  sheep-dog-dev-svc-maven-plugin:
    uses: ./.github/workflows/release.yml
    with:
      project: 'sheep-dog-dev-svc-maven-plugin'
      plugin: 'Maven'
    secrets: inherit            